"""added image

Revision ID: 0b25b3ce9be6
Revises: be67012c1831
Create Date: 2024-07-11 22:23:48.694976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b25b3ce9be6'
down_revision: Union[str, None] = 'be67012c1831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image', sa.String(), nullable=True))
    op.add_column('user', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image')
    op.drop_column('project', 'image')
    # ### end Alembic commands ###
