"""added is_bot

Revision ID: 121a4ad75384
Revises: 965d8d02d1d1
Create Date: 2024-08-29 10:43:11.914349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121a4ad75384'
down_revision: Union[str, None] = '965d8d02d1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_bot', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_bot')
    # ### end Alembic commands ###
