"""backref -> back_populates v.3

Revision ID: 3a572fb42f1d
Revises: ba749b06c222
Create Date: 2024-07-12 21:41:03.787927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a572fb42f1d'
down_revision: Union[str, None] = 'ba749b06c222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
