"""nullable true to filter

Revision ID: be67012c1831
Revises: dd0902fa5c7d
Create Date: 2024-07-11 21:18:34.832167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be67012c1831'
down_revision: Union[str, None] = 'dd0902fa5c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filter', 'project_uni_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('filter', 'project_topic',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('filter', 'profile_uni_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('filter', 'profile_topic',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filter', 'profile_topic',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('filter', 'profile_uni_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('filter', 'project_topic',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('filter', 'project_uni_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
