"""initial

Revision ID: dd0902fa5c7d
Revises: 
Create Date: 2024-07-06 10:44:48.460973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0902fa5c7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uni',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uni_short_name'), 'uni', ['short_name'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('info', sa.String(length=700), nullable=True),
    sa.Column('skills', sa.String(length=700), nullable=True),
    sa.Column('topic', sa.String(length=30), nullable=True),
    sa.Column('uni_id', sa.Integer(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('person_iter', sa.Integer(), nullable=False),
    sa.Column('project_iter', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['uni.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_user_topic'), 'user', ['topic'], unique=False)
    op.create_table('banned_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('project_uni_id', sa.Integer(), nullable=False),
    sa.Column('project_topic', sa.String(length=30), nullable=False),
    sa.Column('profile_uni_id', sa.Integer(), nullable=False),
    sa.Column('profile_topic', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_uni_id'], ['uni.id'], ),
    sa.ForeignKeyConstraint(['project_uni_id'], ['uni.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_telegram_id'), 'filter', ['telegram_id'], unique=True)
    op.create_table('premium',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_telegram_id'), 'premium', ['telegram_id'], unique=True)
    op.create_table('project',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('info', sa.String(length=1000), nullable=False),
    sa.Column('requirements', sa.String(length=1000), nullable=False),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uni_id'], ['uni.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_topic'), 'project', ['topic'], unique=False)
    op.create_table('banned_project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('invite')
    op.drop_table('banned_project')
    op.drop_index(op.f('ix_project_topic'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_premium_telegram_id'), table_name='premium')
    op.drop_table('premium')
    op.drop_index(op.f('ix_filter_telegram_id'), table_name='filter')
    op.drop_table('filter')
    op.drop_table('banned_user')
    op.drop_index(op.f('ix_user_topic'), table_name='user')
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_uni_short_name'), table_name='uni')
    op.drop_table('uni')
    # ### end Alembic commands ###
